name: cicd01.yml
on:
  push:
    branches:
      - main

jobs:
  MY-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world"
      - name: multiple command
        run: |
          echo "good"
          echo "morning"

      - name: github actions
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
